Fix commands without file loaded in gdb (#223)
* Fix start, entry commands without file loaded in gdb

Both `entry` and `start` commands fails when there is no file loaded in gdb:
```
$ gdb -q
Loaded 106 commands.  Type pwndbg [filter] for a list.
pwndbg> entry
Traceback (most recent call last):
  File "/home/dc/installed/pwndbg/pwndbg/commands/__init__.py", line 57, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/installed/pwndbg/pwndbg/commands/start.py", line 67, in entry
    gdb.execute(run, from_tty=False)
gdb.error: No executable file specified.
Use the "file" or "exec-file" command.
```

The patch fixes those issues by introducing `pwndbg.commands.OnlyWithFile` decorator.

* Use pwndbg.commands.OnlyWithFile in rop* commands

* Use pwndbg.commands.OnlyWithFile in elf*, *plt commands

Also refactored the file a bit.

* Use pwndbg.commands.OnlyWithFile in r2 command

* Use pwndbg.commands.OnlyWithFile in errno command

* Use pwndbg.commands.OnlyWithFile in checksec command

* Remove redundant file check in elf.py

* Make save_ida command available only with ida

When there is no file and ida an excetion is thrown:
```
pwndbg> save_ida
Traceback (most recent call last):
  File "/home/dc/installed/pwndbg/pwndbg/ida.py", line 57, in init_ida_rpc_client
    _ida.here()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected
```